FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY src/frontend-api/requirements-frontend.txt .

RUN pip install --no-cache-dir -r requirements-frontend.txt

COPY src/config.py src/
COPY src/frontend-api/ ./src/frontend-api/

EXPOSE 7860

CMD ["python", "src/frontend-api/gradio_app.py"]