FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY src/backend-api/requirements-backend.txt .

RUN pip install --no-cache-dir -r requirements-backend.txt

COPY src/config.py src/
COPY src/backend-api/ ./src/backend-api/
COPY model/ ./model/

EXPOSE 90

CMD ["uvicorn", "src.backend-api.api:app", "--host", "0.0.0.0", "--port", "90"]